/**
 * Generates an open (no-auth) wrapper for MCP worker bundles.
 *
 * This wrapper sits in front of the MCP worker and exposes /mcp without
 * any authentication. It also accepts /mcp/t/{token} for compatibility
 * and rewrites it to /mcp.
 */

/**
 * Generate the open wrapper module code.
 *
 * @param durableObjectClassName - The DO class to re-export (e.g., "ZoteroMCP")
 */
export function generateOpenWrapper(
  durableObjectClassName: string
): string {
  return `
// ─── Open (No Auth) Wrapper ───
// Auto-generated by mcp-deploy. Do not edit.

import OriginalWorker from './original.mjs';
export { ${durableObjectClassName} } from './original.mjs';

export default {
  fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Health check — no secrets exposed
    if (url.pathname === '/') {
      return new Response(
        JSON.stringify({
          name: 'mcp-server',
          status: 'ok',
        }),
        { headers: { 'content-type': 'application/json' } }
      );
    }

    // Accept /mcp/t/{token} and rewrite to /mcp for compatibility
    const tokenMatch = url.pathname.match(/^\\/mcp\\/t\\/([^/]+)(\\/.*)?$/);
    if (tokenMatch) {
      const rewrittenPath = '/mcp' + (tokenMatch[2] || '');
      const rewrittenUrl = new URL(rewrittenPath, url.origin);
      rewrittenUrl.search = url.search;
      const rewrittenRequest = new Request(rewrittenUrl.toString(), request);
      return OriginalWorker.fetch(rewrittenRequest, env, ctx);
    }

    return OriginalWorker.fetch(request, env, ctx);
  },
};
`.trim();
}
